/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ROS 2 Robotics Education",
  "tagline": "Practical mastery of ROS 2 middleware to control humanoid robots",
  "favicon": "img/favicon.ico",
  "url": "https://your-docusaurus-site.example.com",
  "baseUrl": "/",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "D:\\Bilal\\Bilal\\Bilal Data\\Hackathon\\hackathon-01\\sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": false,
        "theme": {
          "customCss": "D:\\Bilal\\Bilal\\Bilal Data\\Hackathon\\hackathon-01\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ]
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Poppins:wght@400;700&family=JetBrains+Mono:wght@400;700&display=swap",
      "type": "text/css",
      "rel": "stylesheet",
      "crossorigin": "anonymous"
    }
  ],
  "themes": [],
  "customFields": {
    "apiUrl": "http://localhost:8000"
  },
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "metadata": [
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0"
      },
      {
        "name": "description",
        "content": "Master robots that bridge digital intelligence and physical reality. Learn ROS 2, simulation, and humanoid control to build the next generation of intelligent robots."
      },
      {
        "name": "keywords",
        "content": "ROS 2, robotics, AI, humanoid robots, simulation, Gazebo, NVIDIA Isaac, machine learning"
      },
      {
        "name": "theme-color",
        "content": "#00d9ff"
      },
      {
        "property": "og:title",
        "content": "ROS 2 Robotics Education"
      },
      {
        "property": "og:description",
        "content": "Master robots that bridge digital intelligence and physical reality. Learn ROS 2, simulation, and humanoid control to build the next generation of intelligent robots."
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:url",
        "content": "https://your-docusaurus-site.example.com"
      },
      {
        "property": "og:image",
        "content": "img/docusaurus-social-card.jpg"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:title",
        "content": "ROS 2 Robotics Education"
      },
      {
        "name": "twitter:description",
        "content": "Master robots that bridge digital intelligence and physical reality. Learn ROS 2, simulation, and humanoid control to build the next generation of intelligent robots."
      },
      {
        "name": "twitter:image",
        "content": "img/docusaurus-social-card.jpg"
      }
    ],
    "headTags": [
      {
        "tagName": "noscript",
        "innerHTML": "<div class=\"noscript-message\" style=\"position: fixed; top: 0; left: 0; width: 100%; background: #ff6b6b; color: white; text-align: center; padding: 10px; z-index: 9999; font-family: sans-serif;\">This website requires JavaScript to function properly. Please enable JavaScript to experience the full interactive features.</div>"
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "preload",
          "href": "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Poppins:wght@400;700&family=JetBrains+Mono:wght@400;700&display=swap",
          "as": "style",
          "onload": "this.onload=null;this.rel='stylesheet'"
        }
      }
    ],
    "fonts": {
      "fontFace": [
        {
          "family": "Inter",
          "urls": [
            "/fonts/Inter-Regular.woff2",
            "/fonts/Inter-Regular.woff"
          ],
          "style": "normal",
          "weight": "400"
        },
        {
          "family": "Inter",
          "urls": [
            "/fonts/Inter-Bold.woff2",
            "/fonts/Inter-Bold.woff"
          ],
          "style": "normal",
          "weight": "700"
        },
        {
          "family": "Poppins",
          "urls": [
            "/fonts/Poppins-Regular.woff2",
            "/fonts/Poppins-Regular.woff"
          ],
          "style": "normal",
          "weight": "400"
        },
        {
          "family": "Poppins",
          "urls": [
            "/fonts/Poppins-Bold.woff2",
            "/fonts/Poppins-Bold.woff"
          ],
          "style": "normal",
          "weight": "700"
        },
        {
          "family": "JetBrains Mono",
          "urls": [
            "/fonts/JetBrainsMono-Regular.woff2",
            "/fonts/JetBrainsMono-Regular.woff"
          ],
          "style": "normal",
          "weight": "400"
        }
      ]
    },
    "navbar": {
      "title": "ROS 2 Robotics Education",
      "logo": {
        "alt": "",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Tutorial"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Tutorial",
              "to": "/docs/module-01-ros2/chapter-01/lesson-01-introduction-to-ros2-concepts"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 ROS 2 Robotics Education. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
